### ISSUE TITLE
You've already registered with that email. Login instead?

### ISSUE THREAD

**Issue by stevejburge** [OSTraining/Simplerenew#292]
Nice touch:
https://segment.com/signup

One we could borrow and use for the username also?
![screen shot 2015-01-02 at 5 15 10 pm](https://cloud.githubusercontent.com/assets/3868028/5600186/f2a9b862-92a2-11e4-9712-a2831cb6f250.png)

**Comment by nicksavov** [comment]
We've already gone one step better :) User verification occurs on subscription pages when not logged in:
https://github.com/OSTraining/Simplerenew/commit/ac1e9675b63cdafa442e3c8b4b8e939a06b38b43

**Comment by stevejburge** [comment]
Thanks. I see this:
![screen shot 2015-01-02 at 5 44 03 pm](https://cloud.githubusercontent.com/assets/3868028/5600395/0e85be74-92a7-11e4-8050-4c953e046ee3.png)

Remember what we said about no errors without a solution? Could we add a login suggestion?

**Comment by stevejburge** [comment]
Related:
![screen shot 2015-01-02 at 5 47 00 pm](https://cloud.githubusercontent.com/assets/3868028/5600418/71db2572-92a7-11e4-8011-9be438ca5cc3.png)

**Comment by billtomczak** [comment]
The way it's supposed to work: 

* if you enter a username that is already in use, we allow them to verify their credentials by entering the correct email and password (twice) for that username. 

* If the username they entered is available, they need to enter an email address that isn't already in use. 

The messaging we're using now was after some conversation with @htmgarcia and (I think) @nicksavov. So - better messaging?

Maybe something to consider is to have a separate area just for error messages rather than individual error messages for each field?

**Comment by nicksavov** [comment]
Could we also make it so that if the email address is taken, authentication also occurs? I think doing that would resolve this issue.

**Comment by billtomczak** [comment]
It's still really a messaging issue. They can authenticate with the correct email address, but they would still need to enter the matching username (and password). Just the reverse of what the current messaging is attempting to say.

**Comment by nicksavov** [comment]
Cool, that makes sense. OK, leave this one for me and I'll work on the text tomorrow and post here for approval.

**Comment by billtomczak** [comment]
btw - you might want to take #287 into account. Similar confusions around the error messages I think.

**Comment by billtomczak** [comment]
An additional complication:  In some cases the user account may not be activated yet due to Joomla configuration and a failed billing verification. They wouldn't be able to log in at all.

Allowing the subscribe form to take the user credentials while not logged in gives them a chance to retry with valid billing info to activate the account.

**Comment by nicksavov** [comment]
Based on Valentin's suggestion at https://github.com/OSTraining/Simplerenew/issues/287#issuecomment-68952309, how about:

"You might have registered already [More Info tooltip]"

**Comment by nicksavov** [comment]
Genius Bill has this solved too via https://github.com/OSTraining/Simplerenew/issues/287#issuecomment-69841723 :)
