### ISSUE TITLE
Simplerenew Configuration Problem: Timeout

### ISSUE THREAD

**Issue by htmgarcia** [OSTraining/Simplerenew#323]
Is this an isue or an integrated security feature from Recurly?
![alert](https://cloud.githubusercontent.com/assets/4999794/6495632/89a0fa82-c291-11e4-8eee-d25b92aec6c7.jpg)

**Comment by billtomczak** [comment]
What did you do when that message appeared? My guess is that SR was trying to get the billing token and Recurly didn't respond quickly enough.

**Comment by htmgarcia** [comment]
I just keep a subscribe page opened for some time, not sure how many minutes. The alert opened automatically.

**Comment by billtomczak** [comment]
I've now seen this message myself. 

For the last several days, everything coming to me from Recurly, whether it's logging into our account or loading anything from either of the apis has been extremely slow. No one else I've contacted seems to be having any trouble so I assume the problem is strictly with my ISP.

But this does mean we may need to do a better job of catching these situations more gracefully. But other than you and me, I haven't heard any other reports on this.

**Comment by nicksavov** [comment]
I've seen it happen one time on Ghost Explained (ironic?)

**Comment by billtomczak** [comment]
Haven't heard any recent reports of this.
