### ISSUE TITLE
Subscribe page in iframe is not working

### ISSUE THREAD

**Issue by gibiwatch** [OSTraining/Simplerenew#382]
I apologise in advance for this "non-standard" usage. For visual integration we are loading the SimpleRenew page in an iframe within the same site. 

It is displayed correctly, and all the interactions seems to be enabled, but when I click on Subscribe I see a "processing" message for a second and then the whole iframe content disappears, blank page. 

I can see no error in browser console or on screen.

Any idea what this could be related to? Is there an easy fix, or am I going to get all kind of troubles trying to make this work?

Thank you very much for any suggestion.

**Comment by billtomczak** [comment]
Before the form is submitted to the server, a javascript request is sent to Recurly with the billing data. Recurly's API responds with a token that can be passed on to the server and used in the php processing code. This prevents all sensitive information (like credit card number) from ever passing through your server and easier PCI certification for anyone using SR.

Putting the form in the iframe may be creating issues with this process. It's likely due to the browser's cross domain security features. For example see https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Content_Scripts/Cross_Domain_Content_Scripts#Cross-domain_XMLHttpRequest.

**Comment by gibiwatch** [comment]
The iframe content comes from the very same site as the main window, so I don't think it's related to cross domain checks. Also, in that case I should get an error in console, which I don't. So this remains a bit of a mistery.

Anyway I understand this is not standard usage so I will try to debug it a bit more by myself.

Thank you!

**Comment by billtomczak** [comment]
yeah - I know it was a bit of wild speculation :)

Do let us know what you find.

**Comment by gibiwatch** [comment]
Just FYI we dropped the "iframe" strategy and we're now opening the regular component page.

**Comment by nicksavov** [comment]
Good idea, gibiwatch! That was going to get messy otherwise.
